### ISSUE TITLE
upnp availability not listed in HACS

### ISSUE THREAD

**Issue by HVR88** [rytilahti/homeassistant-upnp-availability#10]
There are no matches for "upnp" in HACS at the moment.

Also, the instructions for HACS installation in the readme here seem to be out of date and don't match the current Home Assistant menu structure - "Community" menu is gone, have to go to "HACS -> Integrations" to search for custom repositories.  Also, after a repository is added, chances are most people will have to clear the cache on their browser to allow an integration to be found via HA's own Integrations list.

**Comment by rytilahti** [comment]
Feel free to create a PR for the doc update for the instructions how to install.

I'm not yet sure why it is not visible in hacs, but there's are also some changes in `async_upnp_client` that would cause it to fail anyway. Since https://github.com/StevenLooman/async_upnp_client/pull/126 `UpnpError` and `UpnpFactory` are not unfortunately exposed anymore directly, but fixing those imports is not enough as there seem to be some other breaking changes (e.g., `async_search` accepts `source_ip` no more) which needs to be fixed to make this work again.
